# Generated by Django 4.0.2 on 2022-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
