# Generated by Django 4.0.2 on 2022-03-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_video_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
